name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # Gera um arquivo novo chamado snake-bw.svg
            # Cores: Fundo(#161b22), Niveis de cinza, Cobra(#ffffff)
            dist/snake-bw.svg?color_snake=#ffffff&color_dots=#161b22,#444c56,#6e7681,#9ca5b1,#e2e4e9
            
      - name: push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
